packages: []
catalogs:
  build:
    tsdown: ^0.21.7
  dev:
    bumpp: ^11.0.1
    pncat: ^0.11.0
    simple-git-hooks: ^2.13.1
    taze: ^19.10.0
    tsx: ^4.21.0
    typescript: ^6.0.2
  inlined:
    validate-npm-package-name: ^7.0.2
  lint:
    '@octohash/eslint-config': ^0.2.9
    eslint: ^10.1.0
    lint-staged: ^16.4.0
  prod:
    fast-npm-meta: ^1.4.2
  test:
    vitest: ^4.1.2
  types:
    '@types/node': ^25.5.0
    '@types/validate-npm-package-name': ^4.0.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
